services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN_HET101=${GITHUB_TOKEN_HET101:-}
        - GITHUB_TOKEN_HETU29=${GITHUB_TOKEN_HETU29:-}
    restart: unless-stopped
